### ISSUE TITLE
Loader Gui is missing

### ISSUE THREAD

**Issue by idkanymore12354902** [Littleratman/Gorilla-Tag-Utilities#2]
The loader GUI is missing, I can still click and inject and do everything, but I couldn't find the inject button.

**Comment by Littleratman** [comment]
If the inject button is missing simply press reload on the top part of the GUI and it should show, if this problem still continues make sure your antivirus is off as maybe it could delete an important dependency!

**Comment by idkanymore12354902** [comment]
Oh thanks it worked, it was my antivirus.
